version: '3.1'
services:
  zoo1:
    image: zookeeper:3.4.11
    restart: always
    hostname: zoo1
    container_name: zk1
    ports:
      - 2181:2181
    volumes:
      - $PWD/zk1/data:/data
      - $PWD/zk1/datalog:/datalog
    environment:
      ZOO_MY_ID: 1
      # ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
      ZOO_SERVERS: server.1=zoo1:2888:3888
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16

  # zoo2:
  #   image: zookeeper:3.4.11
  #   restart: always
  #   hostname: zoo2
  #   container_name: zk2
  #   ports:
  #     - 2182:2181
  #   volumes:
  #     - $PWD/zk2/data:/data
  #     - $PWD/zk2/datalog:/datalog
  #   environment:
  #     ZOO_MY_ID: 2
  #     ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888

  # zoo3:
  #   image: zookeeper:3.4.11
  #   restart: always
  #   hostname: zoo3
  #   container_name: zk3
  #   ports:
  #     - 2183:2181
  #   volumes:
  #     - $PWD/zk3/data:/data
  #     - $PWD/zk3/datalog:/datalog
  #   environment:
  #     ZOO_MY_ID: 3
  #     ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888